import { StyleSheet } from 'react-native';
import { colors } from '../../shared/theme';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  center: {
    flex: 1,
    backgroundColor: colors.background,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  message: { color: colors.muted, fontSize: 16, marginTop: 12, textAlign: 'center' },
  errorText: { color: colors.msgError, fontSize: 16, fontWeight: '600', marginBottom: 20, textAlign: 'center' },
  retryButton: { backgroundColor: colors.accent, paddingHorizontal: 24, paddingVertical: 12, borderRadius: 8 },
  retryText: { color: colors.textOnDark, fontWeight: '600' },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  topBarButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  starButton: { alignItems: 'center', justifyContent: 'center' },
  sortBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.deep,
  },
  chapterCount: { color: colors.muted, fontSize: 12 },
  sortToggle: { paddingHorizontal: 4, paddingVertical: 4 },
  sortToggleText: { color: colors.accent, fontSize: 13, fontWeight: '600' },

  // ── sort config modal (was chapter-sort-config-modal.styles.ts — folded into the screen) ──
  sortModalBackdrop: {
    flex: 1,
    backgroundColor: colors.overlayHeavy,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 28,
  },
  sortModalCard: {
    backgroundColor: colors.card,
    borderRadius: 16,
    paddingVertical: 24,
    paddingHorizontal: 24,
    width: '100%',
    gap: 12,
  },
  sortModalTitle: { color: colors.textOnDark, fontSize: 17, fontWeight: '700' },
  sortModalOverrideNote: { color: colors.white60, fontSize: 12, lineHeight: 16 },
  sortModalResetBtn: { alignSelf: 'flex-start', paddingVertical: 4 },
  sortModalResetText: { color: colors.accent, fontSize: 13, fontWeight: '600' },
  sortModalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 4 },
  sortModalBtn: { paddingHorizontal: 18, paddingVertical: 10, borderRadius: 10, minWidth: 80, alignItems: 'center' },
  sortModalBtnPrimary: { backgroundColor: colors.accent },
  sortModalBtnSecondary: { backgroundColor: 'transparent', borderWidth: 1, borderColor: colors.white20 },
  sortModalBtnLabelPrimary: { color: colors.textOnDark, fontSize: 14, fontWeight: '600' },
  sortModalBtnLabelSecondary: { color: colors.white80, fontSize: 14, fontWeight: '600' },
});
