import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#1A1A2E' },
  center: {
    flex: 1,
    backgroundColor: '#1A1A2E',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  message: { color: '#A0AEC0', fontSize: 16, marginTop: 12, textAlign: 'center' },
  errorText: { color: '#FC8181', fontSize: 16, fontWeight: '600', marginBottom: 8, textAlign: 'center' },
  errorDetail: { color: '#A0AEC0', fontSize: 13, marginBottom: 20, textAlign: 'center' },
  retryButton: { backgroundColor: '#E94560', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 8 },
  retryText: { color: '#FFFFFF', fontWeight: '600' },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  topBarButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  starButton: { alignItems: 'center', justifyContent: 'center' },
  sortBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#0F3460',
  },
  chapterCount: { color: '#A0AEC0', fontSize: 12 },
  sortToggle: { paddingHorizontal: 4, paddingVertical: 4 },
  sortToggleText: { color: '#E94560', fontSize: 13, fontWeight: '600' },

  // ── sort config modal (was chapter-sort-config-modal.styles.ts — folded into the screen) ──
  sortModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.72)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 28,
  },
  sortModalCard: {
    backgroundColor: '#16213E',
    borderRadius: 16,
    paddingVertical: 24,
    paddingHorizontal: 24,
    width: '100%',
    gap: 12,
  },
  sortModalTitle: { color: '#FFFFFF', fontSize: 17, fontWeight: '700' },
  sortModalOverrideNote: { color: 'rgba(255,255,255,0.6)', fontSize: 12, lineHeight: 16 },
  sortModalResetBtn: { alignSelf: 'flex-start', paddingVertical: 4 },
  sortModalResetText: { color: '#E94560', fontSize: 13, fontWeight: '600' },
  sortModalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 4 },
  sortModalBtn: { paddingHorizontal: 18, paddingVertical: 10, borderRadius: 10, minWidth: 80, alignItems: 'center' },
  sortModalBtnPrimary: { backgroundColor: '#E94560' },
  sortModalBtnSecondary: { backgroundColor: 'transparent', borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' },
  sortModalBtnLabelPrimary: { color: '#FFFFFF', fontSize: 14, fontWeight: '600' },
  sortModalBtnLabelSecondary: { color: 'rgba(255,255,255,0.80)', fontSize: 14, fontWeight: '600' },
});
