import { createStyles } from '../../../../shared/theme';
export const alertStyles = createStyles(({ colors, text, line, spacing, radius, border, alpha }) => ({
    backdrop: {
      flex: 1,
      backgroundColor: alpha(colors.surface.dim, 0.72),
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: spacing[8],
    },
    card: {
      backgroundColor: colors.surface.secondary,
      borderRadius: radius.large,
      paddingVertical: spacing[8],
      paddingHorizontal: spacing[8],
      width: '100%',
      gap: spacing[5],
      shadowColor: colors.surface.dim,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.45,
      shadowRadius: 16,
      elevation: 12,
    },
    title: {
      color: colors.text.emphasis,
      fontSize: text.size[5],
      fontWeight: text.weight.bold,
      letterSpacing: 0.1,
    },
    message: {
      color: alpha(colors.text.button.secondary, 0.8),
      fontSize: text.size[3],
      lineHeight: line.height[6],
    },
    actions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      flexWrap: 'wrap',
      gap: spacing[4],
      marginTop: spacing[2],
    },
    btn: {
      paddingHorizontal: spacing[6],
      paddingVertical: spacing[4],
      borderRadius: radius.medium,
      minWidth: 80,
      alignItems: 'center',
    },
    btnPressed: { opacity: 0.75 },
    btnPrimary: { backgroundColor: colors.button.primary },
    btnDestructive: { backgroundColor: colors.button.destructive },
    btnSecondary: {
      backgroundColor: 'transparent',
      borderWidth: border.medium,
      borderColor: alpha(colors.border.secondary, 0.2),
    },
    btnLabel: { fontSize: text.size[3], fontWeight: text.weight.bold },
    btnLabelPrimary: { color: colors.text.button.primary },
    btnLabelDestructive: { color: colors.text.button.destructive },
    btnLabelSecondary: { color: alpha(colors.text.button.secondary, 0.8) },
}));

