import { createStyles } from '../../../../shared/theme';
export const headerStyles = createStyles(({ colors, text, line, spacing, radius, gutter }) => ({
    root: { padding: gutter },
    topRow: { flexDirection: 'row' },
    cover: { width: 100, aspectRatio: 2 / 3, borderRadius: radius.medium, backgroundColor: colors.surface.tertiary },
    info: { flex: 1, marginLeft: spacing[5], justifyContent: 'flex-start' },
    name: { color: colors.text.title.primary, fontSize: text.size[5], fontWeight: text.weight.bold },
    detailRow: { flexDirection: 'row', marginTop: spacing[3], alignItems: 'flex-start' },
    detailLabel: { color: colors.text.secondary, fontSize: text.size[2], marginRight: spacing[2] },
    detailValue: { color: colors.text.primary, fontSize: text.size[2], flex: 1 },
    detailBlock: { marginTop: spacing[3] },
    detailListItem: { color: colors.text.primary, fontSize: text.size[2], marginTop: spacing[1] },
    abandonedBadge: {
      marginTop: spacing[3],
      alignSelf: 'flex-start',
      backgroundColor: colors.surface.secondary,
      borderRadius: radius.small,
      paddingHorizontal: spacing[3],
      paddingVertical: spacing[2],
    },
    abandonedBadgeText: { color: colors.text.secondary, fontSize: text.size[1], fontWeight: text.weight.bold },
    summary: { color: colors.text.primary, fontSize: text.size[3], marginTop: spacing[5], lineHeight: line.height[4] },
    summaryToggle: { color: colors.text.link.primary, fontSize: text.size[3], fontWeight: text.weight.bold, marginTop: spacing[2] },
    summaryToggleHidden: { opacity: 0 },
    chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[3], marginTop: spacing[5] },
    chip: { backgroundColor: colors.surface.secondary, borderRadius: radius.small, paddingHorizontal: spacing[4], paddingVertical: spacing[2] },
    chipText: { color: colors.text.primary, fontSize: text.size[2] },
    actionButton: {
      marginTop: spacing[6],
      backgroundColor: colors.button.primary,
      borderRadius: radius.medium,
      paddingVertical: spacing[5],
      paddingHorizontal: spacing[6],
      alignSelf: 'stretch',
      alignItems: 'center',
    },
    // flexShrink lets the ellipsis kick in instead of the text forcing the button wider.
    actionButtonText: { color: colors.text.button.primary, fontSize: text.size[3], fontWeight: text.weight.bold, flexShrink: 1 },
}));

