import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.72)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 28,
  },
  card: {
    backgroundColor: '#16213E',
    borderRadius: 16,
    paddingVertical: 24,
    paddingHorizontal: 24,
    width: '100%',
    gap: 16,
    maxHeight: '80%',
  },
  title: { color: '#FFFFFF', fontSize: 17, fontWeight: '700' },
  header: { flexDirection: 'row', gap: 12 },
  cover: { width: 64, height: 91, borderRadius: 6, flexShrink: 0 },
  headerInfo: { flex: 1, justifyContent: 'center', gap: 4 },
  seriesName: { color: '#FFFFFF', fontSize: 15, fontWeight: '600' },
  bodyText: { color: '#A0AEC0', fontSize: 13 },
  timestamp: { color: '#718096', fontSize: 12 },
  chaptersSection: { gap: 6 },
  chaptersTitle: { color: 'rgba(255,255,255,0.6)', fontSize: 12, fontWeight: '600' },
  chaptersList: { maxHeight: 140 },
  chapterRow: { color: '#E2E8F0', fontSize: 13, paddingVertical: 4 },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  actionBtn: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 10, alignItems: 'center' },
  actionBtnSecondary: { backgroundColor: 'transparent', borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' },
  actionBtnDanger: { backgroundColor: 'transparent', borderWidth: 1, borderColor: '#E94560' },
  actionLabelSecondary: { color: 'rgba(255,255,255,0.80)', fontSize: 13, fontWeight: '600' },
  actionLabelDanger: { color: '#E94560', fontSize: 13, fontWeight: '600' },
  closeBtn: { alignSelf: 'center', paddingVertical: 8 },
  closeLabel: { color: 'rgba(255,255,255,0.6)', fontSize: 13, fontWeight: '600' },
});
