import { StyleSheet } from 'react-native';
import { colors } from '../../../../shared/theme';

export const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: colors.overlayHeavy,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 28,
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: 16,
    paddingVertical: 24,
    paddingHorizontal: 24,
    width: '100%',
    gap: 16,
    maxHeight: '80%',
  },
  title: { color: colors.textOnDark, fontSize: 17, fontWeight: '700' },
  header: { flexDirection: 'row', gap: 12 },
  cover: { width: 64, height: 91, borderRadius: 6, flexShrink: 0 },
  headerInfo: { flex: 1, justifyContent: 'center', gap: 4 },
  seriesName: { color: colors.textOnDark, fontSize: 15, fontWeight: '600' },
  bodyText: { color: colors.muted, fontSize: 13 },
  timestamp: { color: colors.mutedAlt, fontSize: 12 },
  chaptersSection: { gap: 6 },
  chaptersTitle: { color: colors.white60, fontSize: 12, fontWeight: '600' },
  chaptersList: { maxHeight: 140 },
  chapterRow: { color: colors.textBright, fontSize: 13, paddingVertical: 4 },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  actionBtn: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 10, alignItems: 'center' },
  actionBtnSecondary: { backgroundColor: 'transparent', borderWidth: 1, borderColor: colors.white20 },
  actionBtnDanger: { backgroundColor: 'transparent', borderWidth: 1, borderColor: colors.accent },
  actionLabelSecondary: { color: colors.white80, fontSize: 13, fontWeight: '600' },
  actionLabelDanger: { color: colors.accent, fontSize: 13, fontWeight: '600' },
  closeBtn: { alignSelf: 'center', paddingVertical: 8 },
  closeLabel: { color: colors.white60, fontSize: 13, fontWeight: '600' },
});
