import { createStyles } from '../../../../shared/theme';
export const detailModalStyles = createStyles(({ colors, text, spacing, radius, border, alpha }) => ({
    backdrop: {
      flex: 1,
      backgroundColor: alpha(colors.surface.dim, 0.72),
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: spacing[8],
    },
    card: {
      backgroundColor: colors.surface.secondary,
      borderRadius: radius.large,
      paddingVertical: spacing[8],
      paddingHorizontal: spacing[8],
      width: '100%',
      gap: spacing[6],
      maxHeight: '80%',
    },
    title: { color: colors.text.title.primary, fontSize: text.size[5], fontWeight: text.weight.bold },
    header: { flexDirection: 'row', gap: spacing[5] },
    cover: { width: 64, aspectRatio: 2 / 3, borderRadius: radius.medium, flexShrink: 0 },
    headerInfo: { flex: 1, justifyContent: 'center', gap: spacing[2] },
    seriesName: { color: colors.text.title.primary, fontSize: text.size[3], fontWeight: text.weight.bold },
    bodyText: { color: colors.text.secondary, fontSize: text.size[3] },
    timestamp: { color: colors.text.secondary, fontSize: text.size[2] },
    chaptersSection: { gap: spacing[3] },
    chaptersTitle: { color: alpha(colors.text.secondary, 0.6), fontSize: text.size[2], fontWeight: text.weight.bold },
    chaptersList: { maxHeight: 140 },
    chapterRow: { color: colors.text.primary, fontSize: text.size[3], paddingVertical: spacing[2] },
    actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[4] },
    actionBtn: { paddingHorizontal: spacing[5], paddingVertical: spacing[4], borderRadius: radius.medium, alignItems: 'center' },
    actionBtnSecondary: { backgroundColor: 'transparent', borderWidth: border.medium, borderColor: alpha(colors.border.secondary, 0.2) },
    actionBtnDanger: { backgroundColor: 'transparent', borderWidth: border.medium, borderColor: colors.border.accent },
    actionLabelSecondary: { color: alpha(colors.text.button.secondary, 0.8), fontSize: text.size[3], fontWeight: text.weight.bold },
    actionLabelDanger: { color: colors.text.link.primary, fontSize: text.size[3], fontWeight: text.weight.bold },
    closeBtn: { alignSelf: 'center', paddingVertical: spacing[4] },
    closeLabel: { color: alpha(colors.text.secondary, 0.6), fontSize: text.size[3], fontWeight: text.weight.bold },
}));

